stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:12-alpine
      shellScript: |-
        env
        apk update && apk upgrade && apk add git
        yarn install
        yarn lint
        yarn build
    envFrom:
    - sourceName: web
      sourceKey: REACT_APP_BASE_URL
      targetKey: REACT_APP_BASE_URL
    - sourceName: web
      sourceKey: REACT_APP_OPENID_CONNECT_CLIENT_ID
      targetKey: REACT_APP_OPENID_CONNECT_CLIENT_ID
    - sourceName: web
      sourceKey: REACT_APP_OPENID_AUDIENCE
      targetKey: REACT_APP_OPENID_AUDIENCE
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile_nginx
      buildContext: .
      tag: web:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/rancher/deployment.yaml
  when:
    branch:
      include:
      - development
notification: {}
