stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:14.16.1-alpine3.13
      shellScript: |-
        env
        apk update && apk upgrade && apk add python2 make g++ git
        yarn install
        yarn lint
        yarn build
    envFrom:
    - sourceName: web
      sourceKey: REACT_APP_BASE_URL
      targetKey: REACT_APP_BASE_URL
    - sourceName: web
      sourceKey: REACT_APP_OPENID_CONNECT_CLIENT_ID
      targetKey: REACT_APP_OPENID_CONNECT_CLIENT_ID
    - sourceName: web
      sourceKey: REACT_APP_OPENID_AUDIENCE
      targetKey: REACT_APP_OPENID_AUDIENCE
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile_unikie_dev_cluster
      buildContext: .
      tag: kleklekle/spia:kaavapino-web-${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/rancher/deployment.yaml
  when:
    branch:
      include:
      - development
notification: {}
