export const confirmationAttributeNames = [
    'vahvista_oas_esillaolo_alkaa', 'vahvista_oas_esillaolo_paattyy',
    'vahvista_oas_esillaolo_alkaa_2', 'vahvista_oas_esillaolo_paattyy_2',
    'vahvista_oas_esillaolo_alkaa_3', 'vahvista_oas_esillaolo_paattyy_3',
    'vahvista_periaatteet_esillaolo_alkaa', 'vahvista_periaatteet_esillaolo_paattyy',
    'vahvista_periaatteet_esillaolo_alkaa_2', 'vahvista_periaatteet_esillaolo_paattyy_2',
    'vahvista_periaatteet_esillaolo_alkaa_3', 'vahvista_periaatteet_esillaolo_paattyy_3',
    'vahvista_periaatteet_lautakunnassa', 'vahvista_periaatteet_lautakunnassa_2',
    'vahvista_periaatteet_lautakunnassa_3', 'vahvista_periaatteet_lautakunnassa_4',
    'vahvista_luonnos_esillaolo_alkaa', 'vahvista_luonnos_esillaolo_paattyy',
    'vahvista_luonnos_esillaolo_alkaa_2', 'vahvista_luonnos_esillaolo_paattyy_2',
    'vahvista_luonnos_esillaolo_alkaa_3', 'vahvista_luonnos_esillaolo_paattyy_3',
    'vahvista_ehdotus_esillaolo', 'vahvista_ehdotus_esillaolo_paattyy',
    'vahvista_kaavaluonnos_lautakunnassa', 'vahvista_kaavaluonnos_lautakunnassa_2',
    'vahvista_kaavaluonnos_lautakunnassa_3', 'vahvista_kaavaluonnos_lautakunnassa_4',
    'vahvista_ehdotus_esillaolo_2', 'vahvista_ehdotus_esillaolo_paattyy_2',
    'vahvista_ehdotus_esillaolo_3', 'vahvista_ehdotus_esillaolo_paattyy_3',
    'vahvista_ehdotus_esillaolo_4', 'vahvista_ehdotus_esillaolo_paattyy_4',
    'vahvista_kaavaehdotus_lautakunnassa', 'vahvista_kaavaehdotus_lautakunnassa_2',
    'vahvista_kaavaehdotus_lautakunnassa_3', 'vahvista_kaavaehdotus_lautakunnassa_4',
    'vahvista_tarkistettu_ehdotus_lautakunnassa', 'vahvista_tarkistettu_ehdotus_lautakunnassa_2',
    'vahvista_tarkistettu_ehdotus_lautakunnassa_3', 'vahvista_tarkistettu_ehdotus_lautakunnassa_4',
  ];
  